### ISSUE TITLE
dune runtest fails on 32bit

### ISSUE THREAD

**Issue by olafhering** [thierry-martinez/pyml#70]
`dune runtest` fails on 32bit (armv6l/armv7l/i586), but succeeds on 64bit:
````
Last lines of build log:
[  176s] Test 'IPython' ... disabled: IPython is not available
[  176s] Test 'Marshal' ... passed
[  176s] Test 'Py.List.of_list' ... passed
[  176s] Test 'Py.List.sort' ... passed
[  176s] Test 'array' ... passed
[  176s] Test 'numpy' ... 
[  176s] Traceback (most recent call last):
[  176s]   File "<string>", line 3, in <module>
[  176s] AssertionError
[  176s] raised an exception: File "pyml_tests.ml", line 532, characters 10-16: Assertion failed
[  176s] Test 'numpy crunch' ... 
[  176s] + echo 'dune runtest failed'
[  176s] dune runtest failed
[  176s] + test -n ''
[  176s] + echo aborting
[  176s] aborting
[  176s] + exit 1
[  176s] error: Bad exit status from /var/tmp/rpm-tmp.ReVzWa (%check)
````

[armv7l-ocaml-pyml.txt](https://github.com/thierry-martinez/pyml/files/7226585/armv7l-ocaml-pyml.txt)

**Comment by thierry-martinez** [comment]
Thank you very much for the report! Should be fixed now.
